# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LvbBMg00Ci0-hVkpLLslD63ZWFv64di
"""

import streamlit as st
import pickle
import numpy as np
from sklearn.preprocessing import StandardScaler, OrdinalEncoder

# Load model
model = pickle.load(open('model_uas.pkl', 'rb'))

# Judul Aplikasi
st.title('Prediksi Biaya Asuransi')
st.write('Dibuat oleh: Ryno Pahlevi Al Ghiffari (NIM: 2021230039)')

# Input Fields
col1, col2 = st.columns(2)

with col1:
    age = st.number_input('Umur', min_value=18, max_value=64, value=30)
    sex = st.selectbox('Jenis Kelamin', ['Perempuan', 'Laki-laki'])
    bmi = st.number_input('BMI', min_value=15.0, max_value=50.0, value=25.0)

with col2:
    children = st.number_input('Jumlah Anak', min_value=0, max_value=5, value=0)
    smoker = st.selectbox('Perokok', ['Tidak', 'Ya'])

# Preprocessing input
def preprocess_input(age, sex, bmi, children, smoker):
    # Konversi kategorikal ke numerik
    sex_map = {'Perempuan': 0, 'Laki-laki': 1}
    smoker_map = {'Tidak': 0, 'Ya': 1}

    # Siapkan data input
    input_data = np.array([
        age,
        sex_map[sex],
        bmi,
        children,
        smoker_map[smoker]
    ]).reshape(1, -1)

    # Standarisasi
    sc = StandardScaler()
    input_data_scaled = sc.fit_transform(input_data)

    return input_data_scaled

# Tombol Prediksi
if st.button('Prediksi Biaya Asuransi'):
    # Preprocessing
    input_scaled = preprocess_input(age, sex, bmi, children, smoker)

    # Prediksi
    prediction = model.predict(input_scaled)

    # Tampilkan hasil
    st.success(f'Estimasi Biaya Asuransi: ${prediction[0]:,.2f}')